language: csharp
solution: BookTracker.sln
mono: none
dotnet: 5.0
script:
  - dotnet restore
  - cd ClientApp
  - npm install
  - npm run test
  - npm run buildCI
  - cd ..
  - dotnet build
after_success:
  - echo frontend tests & dotnet build succeeded
after_failure:
  - echo frontend tests or dotnet build failed