language: csharp
solution: BookTracker.sln
mono: none
dotnet: 3.1
script:
  - dotnet restore
  - npm install
  - npm run test
after_success:
  - echo dotnet succeeded
after_failure:
  - echo dotnet failed